### ISSUE TITLE
Ajouter infos dans l'application

### ISSUE THREAD

**Issue by marlabe** [cr-crme/mon_stage_en_images#31]
J'aimerais ajouter des éléments de formation pour la théorie derrière l'application: https://www.irsst.qc.ca/media/documents/PubIRSST/DF-1071.pdf?v=2020-06-25 
[Annexe 2 Banque de questions-juin.pdf](https://github.com/cr-crme/defi_photo/files/14012038/Annexe.2.Banque.de.questions-juin.pdf)

J'aimerais aussi ajouter plus de questions dans une banque de questions (voir pj)

J'aimerais changer le titre de l'Outil pour "Mon stage en image"

**Comment by pariterre** [comment]
> J'aimerais changer le titre de l'Outil pour "Mon stage en image"

Done

**Comment by pariterre** [comment]
> J'aimerais aussi ajouter plus de questions dans une banque de questions (voir pj)

This relates to #34 which has been decided to be put on the website (as pdf links are not optimal)
