### ISSUE TITLE
Précision pour petites modif

### ISSUE THREAD

**Issue by marlabe** [cr-crme/mon_stage_en_images#34]
Menu: Gestion des questions avant Résumé des réponses dans le menu. 
Ajouter quelque part un lien vers un document pdf (site Web de la Chaire) comprenant une banque de questions
Aussi quand Sami sera de retour: faire un lien vers une banque de questions plus large sur le site Web AdoPrevit
Update du contrat d'utilisation: Les questions générées pourront servir à enrichir la banque de questions offertes sur le site AdoPrevit. Mettre aussi que les données d'élèves seront supprimé à chaque année, à l'été - pour refuser, contacter ..@mmm

**Comment by pariterre** [comment]
> Menu: Gestion des questions avant Résumé des réponses dans le menu.

Done

**Comment by pariterre** [comment]
> AdoPrevit. Mettre aussi que les données d'élèves seront supprimé à chaque année, à l'été - pour refuser, contacter ..@mmm

Added in the section "Conservation de Vos Données Personnelles" :  "De façon annuelle, à l'extérieur de la période scolaire, les Données Personnelles pourront être supprimées par la Société sans autres préavis."

**Comment by pariterre** [comment]
> Ajouter quelque part un lien vers un document pdf (site Web de la Chaire) comprenant une banque de questions

Done
